### ISSUE TITLE
Authentication with jodel failed

### ISSUE THREAD

**Issue by iYsood** [simonbs/jodelihood#2]
Hello sir, I've some trouble with this project, 
when I run app after install depends NPM, project doesn't work!

Authentication with jodel (please ensure that you have given jodelihood access to your location)

and The browser was given permission :(

**Comment by cmantsch** [comment]
Read the first section in the Readme, this is no longer functional

**Comment by simonbs** [comment]
It's true what @cmantsch writes. This is not expected to work anymore.
