### ISSUE TITLE
error when running npm install

### ISSUE THREAD

**Issue by Archviz360** [simonbs/jodelihood#3]
actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\dacia\Desktop\jodelihood-master\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\dacia\Desktop\jodelihood-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\dacia\\Desktop\\jodelihood-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@19.0.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\dacia\Desktop\jodelihood-master\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\dacia\Desktop\jodelihood-master\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\dacia\Desktop\jodelihood-master\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\dacia\Desktop\jodelihood-master\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\dacia\Desktop\jodelihood-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\dacia\Desktop\jodelihood-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\dacia\Desktop\jodelihood-master\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\dacia\Desktop\jodelihood-master\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\dacia\Desktop\jodelihood-master\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\dacia\Desktop\jodelihood-master\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\dacia\Desktop\jodelihood-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\dacia\Desktop\jodelihood-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\dacia\AppData\Local\Programs\Python\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\dacia\AppData\Local\Programs\Python\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:412:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dacia\\Desktop\\jodelihood-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\dacia\Desktop\jodelihood-master\node_modules\node-sass
npm ERR! gyp ERR! node -v v19.0.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dacia\AppData\Local\npm-cache\_logs\2022-10-30T18_59_21_104Z-debug-0.log
PS C:\Users\dacia\Desktop\jodelihood-master> npm run deploy

> jodelihood@1.0.0 deploy
> NODE_ENV=production webpack -p && cp app/index.html build/

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\dacia\Desktop\jodelihood-master>  npm start

> jodelihood@1.0.0 start
> node server.js

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'finalhandler'
Require stack:
- C:\Users\dacia\Desktop\jodelihood-master\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\dacia\Desktop\jodelihood-master\server.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\dacia\\Desktop\\jodelihood-master\\server.js' ]
}

Node.js v19.0.0
PS C:\Users\dacia\Desktop\jodelihood-master> npm run dev

> jodelihood@1.0.0 dev
> webpack-dev-server --content-base app

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\dacia\Desktop\jodelihood-master> pip install webpack-dev-server
ERROR: Could not find a version that satisfies the requirement webpack-dev-server (from versions: none)
ERROR: No matching distribution found for webpack-dev-server

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\Users\dacia\Desktop\jodelihood-master>

**Comment by simonbs** [comment]
This repository is no longer under development.
